name: 02 DUMP
on:
  push:
    paths: [".github/workflows/02-*"]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github) }}"
      - run: echo "${{ toJSON(runner) }}"
      - run: echo "${{ toJSON(job) }}"
      - run: pwd && uname -a && id -a && set

# other objects: strategy, matrix
