name: 02 DUMP
on:
  push:
    paths: [".github/workflows/02-*"]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github) }}"
      - run: echo "${{ toJSON(runner) }}"
      - run: echo "${{ toJSON(job) }}"
      - run: set && id -a && pwd && uname -a

# other objects: strategy, matrix
