name: 04 Chain
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "JOB_1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "JOB_2"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: |
          echo "JOB_3"
