name: 05 Outputs
on:
  push:
    paths: [".github/workflows/05-*"]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.step1.outputs.var }}
      var2: ${{ steps.step2.outputs.var }}
      var3: ${{ steps.step3.outputs.var }}
    steps:
      - id: step1
        run: echo "var=HELLO" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "var=WORLD" >> $GITHUB_OUTPUT
      - id: step3
        run: echo "var=$(tar czf - . | openssl base64 | tr '\n' '|')" >> $GITHUB_OUTPUT
      - run: echo "EEEEEEEEEE=AAAAAAAAA" > $GITHUB_ENV
      - run: echo "${{env.EEEEEEEEEE}}; set
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "${{needs.job1.outputs.var1}} ${{needs.job1.outputs.var2}}"
          echo "${{needs.job1.outputs.var3}}" | tr '|' '\n' | openssl base64 -d | tar tvzf -
