name: 09 Secrets
on:
  push:
    paths: [".github/workflows/09-*"]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VAR: ${{secrets.FOO}}
    steps:
      - run: |
          [ -z "$VAR" ] && echo "No VAR provided, provide a valid FOO secret" && exit 1
          echo "$VAR"