name: 12 Service
on:
  push:
    paths: [".github/workflows/12-*"]
jobs:
  service-job:
    runs-on: ubuntu-latest
    services:
      service1:
        image: selenium/standalone-chrome
        ports:
          # - 4444:4444 # assign a fixed host port
          - 4444/tcp  # assign a random free host port

    steps:
      - run: |
          echo "${{ toJSON(job.services) }}"
          PORT=${{job.services.service1.ports[4444]}}
          wget http://localhost:$PORT
