name: 12 Use Action
on:
  push:
    paths: [".github/workflows/13-*"]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
         uname -a
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.8
      - run: |
         uname -a
