name: 14 Check User
on:
  push:
    branches: [main]
    paths: [".github/workflows/14-*"]
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          username: ${{github.triggering_actor}}
          require: 'write'
      - name: Fail on external workflow triggering
        if: ${{ steps.checkUser.outputs.require-result != 'true' }}
        run: |
          echo "🚫 **${{ github.actor }}** is an external contributor, a **${{github.repository}}** team member has to review this changes and re-run this build" \
          | tee -a $GITHUB_STEP_SUMMARY && exit 1
      - name: Check secrets
        run: |
          [ -z "${{secrets.TB_LICENSE}}" ] \
            && echo "🚫 **TB_LICENSE** is not defined, check that **${{github.repository}}** repo has a valid secret" \
            | tee -a $GITHUB_STEP_SUMMARY && exit 1 || exit 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}          
      - name: Show Git Status
        run: git status
